### ISSUE TITLE
Overlapping errors kill the blue underline, create bad corrections

### ISSUE THREAD

**Issue by snomos** [divvun/libreoffice-divvun#11]
Check the following screen shots:

1. Missing space after parenthesis, the following word correctly spelled - error detected and with a proper correction compared to the blue underline:
<img width="594" alt="Skjermbilde 2019-09-12 kl  12 12 24" src="https://user-images.githubusercontent.com/1255285/64772105-bca0bd80-d558-11e9-9de0-e3c9cf73d3d4.png">

2. The following word misspelled, but now with a space after the parenthesis - misspelling detected and corrected as it should:
<img width="594" alt="Skjermbilde 2019-09-12 kl  12 12 44" src="https://user-images.githubusercontent.com/1255285/64772273-fc67a500-d558-11e9-909e-7e3719e025b8.png">

3. No space after the parenthesis, AND the following word misspelled - the blue underline is now only on the parenthesis, making it hard to see and hit:
<img width="594" alt="Skjermbilde 2019-09-12 kl  12 14 44" src="https://user-images.githubusercontent.com/1255285/64772373-2caf4380-d559-11e9-9eff-9f58549c9048.png">

4. ... but worse, the suggestion is still as if the blue underline covers the following word:
<img width="594" alt="Skjermbilde 2019-09-12 kl  12 13 09" src="https://user-images.githubusercontent.com/1255285/64772533-6da75800-d559-11e9-8211-dd0614b0c093.png">

5. ... which leads to the corrected text becoming meaningless:
<img width="594" alt="Skjermbilde 2019-09-12 kl  12 13 25" src="https://user-images.githubusercontent.com/1255285/64772663-aa734f00-d559-11e9-9b78-e9660f3ec7ea.png">

The bug is restricted to LO. The command line interface properly suppresses the second of the two overlapping errors:

```javascript
$ echo 'Vuoigatvuođa Lávdegotti (SVL)čilghus' | divvun-checker -a se.zcheck | jq .
{
  "errs": [
    [
      ")čilghus",
      28,
      36,
      "no-space-after-parent-end",
      "[SE] Parenthesis missing space",
      [
        ") čilgehus"
      ],
      "[SE] Parenthesis missing space"
    ]
  ],
  "text": "Vuoigatvuođa Lávdegotti (SVL)čilghus"
}
```

The zcheck file is [available for download](https://www.dropbox.com/s/qmcn2i00e49sy27/se.zcheck?dl=0) for a limited time.

Env.: newest of everything (hfst, vislcg3, libdivvun, etc).

**Comment by unhammer** [comment]
Eg får

![Skjermbilete_2019-09-12_15-03-04](https://user-images.githubusercontent.com/56868/64789743-39419500-d575-11e9-958e-c1f426d0fc78.png)

med den zcheck-en, oxt plz?

**Comment by snomos** [comment]
[oxt](https://www.dropbox.com/s/6im9l7wu86mqmj4/divvun.oxt?dl=0) (ikkje permanent lenke)

**Comment by snomos** [comment]
Fiksa i release 0.3.6.
