### ISSUE TITLE
use <description>, not <title>, in right-click error messages

### ISSUE THREAD

**Issue by unhammer** [divvun/libreoffice-divvun#6]
https://github.com/divvun/libdivvun/issues/19 put the errors.xml `<description>` in the JSON's message field, but we still need to use that in LO for the right-click error messages (which come through the python API, not the JSON output).

**Comment by Trondtr** [comment]
Unfortunately, this issue is still open (unless I have missed an update, but I downloaded the divvun.oxt (?) from Sjur that was claimed to fix it. The behaviour I now get is that xxx from <error><header><title>xxx</title> is displayed BOTH in the Preferences > Language Settings > Divvun list AND in the context-sensitive header when I press ctrl-click on the error. The yyy in <description>yyy</description></body></error> is nowhere to be seen. This holds for both sme and fao grammarchecker.

**Comment by Trondtr** [comment]
oops, the editor did something with my error report. By "yyy in yyy" I meant  to refer to the content in the description node in the body of the error node in errors.source.xml. Bottom line is thus that (for me, at least), the issue is not fixed, despite my new divvun.oxt

**Comment by unhammer** [comment]
Eg får ![desc](https://user-images.githubusercontent.com/56868/53731484-2ee26800-3e7b-11e9-87c4-ad0572dab6b5.png) 

– kan du lasta opp fila `pythonpath/LODivvun/GrammarChecker.py` som ligg inni den divvun.oxt-fila du bruker?

**Comment by unhammer** [comment]
Eller, viss det var den frå https://giella.zulipchat.com/#narrow/stream/129301-gramcheck/topic/Feilmelding.20vs.20tittel så ser eg at den ikkje er nyaste utgåve:

```
$ diff oxt/pythonpath/LODivvun/GrammarChecker.py /tmp/unzipped/pythonpath/LODivvun/GrammarChecker.py
113c113
<                               comment = dError.dsc
---
>                               comment = dError.msg
118,122c118,121
<                               if False:  # We are not web yet, TODO
<                                   detailUrl = PropertyValue()
<                                   detailUrl.Name = "FullCommentURL"
<                                   detailUrl.Value = "http://divvun.no/gchelp/" + aLocale.Language + "/" + ruleIdentifier + ".html"
<                                   gcError.aProperties = (detailUrl,)
---
>                               detailUrl = PropertyValue()
>                               detailUrl.Name = "FullCommentURL"
>                               detailUrl.Value = "http://divvun.no/gchelp/" + aLocale.Language + "/" + ruleIdentifier + ".html"
>                               gcError.aProperties = (detailUrl,)
```
